insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Dimethicone', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Dextromethorphan HBr, Doxylamine succinate', 'Etiam justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate, Octisalate, and Oxybenzone', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Isosorbide Mononitrate', 'Cras in purus eu magna vulputate luctus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levetiracetam', 'Duis ac nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aluminum Zirconium Tetrachlorohydrex GLY', 'Cras in purus eu magna vulputate luctus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'methylphenidate hydrochloride', 'Quisque porta volutpat erat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Tobacco Leaf', 'Aenean sit amet justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'diclofenac sodium', 'Proin interdum mauris non ligula pellentesque ultrices.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levothyroxine Sodium', 'Nunc nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'homatropine hydrobromide', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Antimony Pentasulfide and Potassium Iodide and Polygala Senega Root', 'Vivamus vel nulla eget eros elementum pellentesque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diphenhydramine HCl, Phenylephrine HCl', 'In congue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'trimethobenzamide hydrochloride', 'Nullam varius.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'terbinafine hydrochloride', 'Aliquam quis turpis eget elit sodales scelerisque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Simethicone', 'Vivamus in felis eu sapien cursus vestibulum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Fexofenadine Hydrochloride', 'Nulla tempus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'lamotrigine', 'Nulla tellus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Zidovudine', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Zinc Oxide', 'Donec quis orci eget orci vehicula condimentum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzocaine 20%, Menthol, Benzalkonium Chloride', 'Etiam justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Methyl Salicylate, Menthol and Capsaicin', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'montelukast sodium', 'Nulla justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ARIPIPRAZOLE', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cilostazol', 'Fusce consequat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'POLYETHYLENE GLYCOL 3350', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Loperamide Hydrochloride', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ibuprofen', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrocodone Bitartrate And Acetaminophen', 'Vivamus tortor.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Clarithromycin', 'Proin interdum mauris non ligula pellentesque ultrices.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'azithromycin', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Diphenhydramine HCl', 'Cras in purus eu magna vulputate luctus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Trazodone Hydrochloride', 'Nam nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Adrenalinum, Belladona, Bromium, Carbo animalis, Colchicum autumnale, Colocynthis, Histaminum hydrochloricum, Hydrstis canadensis, Kali carbonicum, Lycopodium clavatum, Mercuris solubilis, Pulsatilla, Urtica urens', 'Donec vitae nisi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'testosterone cypionate', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Giant Wild Rye', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE', 'Nullam varius.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benadryl', 'In eleifend quam a odio.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Asterias rubens, Aur. met.,Belladonna, Benzoicum acidum, Berber. vulg., Bryonia, Calc. carb., Cantharis, Ceanothus, Chelidonium majus Chionanthus virginica, Cinchona, Dioscorea ,Iris versicolor, Nat. carb., Nux vom., Ptelea, Carduus mar., Echinacea, Solidago, Taraxacum', 'Donec semper sapien a libero.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Norethindrone Acetate/Ethinyl Estradiol', 'Nulla tempus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Chlorpheniramine Maleate, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', 'Nam nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Mucor racemosus', 'Vestibulum rutrum rutrum neque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Meprobamate', 'In congue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ZOLPIDEM TARTRATE', 'Integer a nibh.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'FOLIC ACID, .BETA.-CAROTENE, ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, DL-, THIAMINE MONONITRATE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE HYDROCHLORIDE, CYANOCOBALAMIN, CALCIUM PANTOTHENATE, CALCIUM CARBONATE, FERROUS FUMARATE, and ZINC OXIDE', 'Maecenas ut massa quis augue luctus tincidunt.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrocortisone', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Corn Smut', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Budesonide', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ANTIMONY POTASSIUM TARTRATE', 'Morbi non quam nec dui luctus rutrum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Russian Olive Elaeagnus angustifolia', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'formoterol fumarate dihydrate', 'Suspendisse potenti.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Camphor Menthol Methyl Salicylate', 'Etiam pretium iaculis justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Simethicone', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ibuprofen', 'Aliquam quis turpis eget elit sodales scelerisque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Felodipine', 'Praesent id massa id nisl venenatis lacinia.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Plantago Primula', 'Quisque porta volutpat erat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'CLINDAMYCIN HYDROCHLORIDE', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Morphine Sulfate', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'Integer ac neque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sulfamethoxazole and Trimethoprim', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'PREGABALIN', 'Donec semper sapien a libero.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'risperidone', 'Nullam porttitor lacus at turpis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Carvedilol', 'In blandit ultrices enim.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sugar Maple', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Echinacea, Petroselinum Sativum, Solidago Virgaurea, Uva-Ursi, Pareira Brava, Glutathione, Kidney', 'Nam dui.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Adrenalinum, Adrenocorticotrophin, Agrimonia eupatoria flos, Anacardium orientale, Antimonium crudum, Calcarea carbonica, Castanea sativa flos, Cortisone aceticum, Fucus vesiculosus, Hypothalamus , Kali bichromicum, Oleander, Pituitarum posterium, Sabadilla, Staphysagria, Thyroidinum', 'Duis consequat dui nec nisi volutpat eleifend.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ferrum phosphoricum', 'In hac habitasse platea dictumst.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ribavirin', 'Integer tincidunt ante vel ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'CAMPHOR, MENTHOL, WHITE PETROLATUM', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'amlodipine besylate and atorvastatin calcium', 'Nunc nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sulfur 30 Special Order', 'Duis consequat dui nec nisi volutpat eleifend.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Stannous Fluoride', 'Quisque id justo sit amet sapien dignissim vestibulum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levonogestrel and Ethinyl Estradiol', 'Duis consequat dui nec nisi volutpat eleifend.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Mometasone Furoate', 'Integer non velit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Naratriptan', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TRICLOSAN', 'Integer a nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aspirin, Caffeine', 'Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'IOPAMIDOL', 'Praesent blandit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ramipril', 'Pellentesque ultrices mattis odio.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Blueberry', 'Phasellus in felis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levetiracetam', 'Mauris sit amet eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Guaifenesin, phenylephrine HCL, Dextromethorphan', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'diphenhydramine hydrochloride', 'Quisque porta volutpat erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE, ZINC OXIDE', 'Proin eu mi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'CEVIMELINE HYDROCHLORIDE', 'In quis justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BENZALKONIUM CHLORIDE', 'Morbi porttitor lorem id ligula.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Baclofen', 'Maecenas ut massa quis augue luctus tincidunt.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Titanium Dioxide and Zinc Oxide', 'Cras non velit nec nisi vulputate nonummy.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Oxcarbazepine', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Metoclopramide', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Causticum, Natrum muriaticum, Nus vomica, Pulsatilla, Sepia, Staphysagria, Thuja occidentalis,', 'Ut tellus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Simvastatin', 'Phasellus sit amet erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'misoprostol', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'DEXTROSE, SODIUM CHLORIDE, and POTASSIUM CHLORIDE', 'Nulla nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Pepper Tree', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lidocaine', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Divalproex Sodium', 'Donec quis orci eget orci vehicula condimentum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'coagulation factor IX human', 'Maecenas pulvinar lobortis est.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'White Petrolatum', 'Pellentesque eget nunc.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', 'Proin eu mi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Fexofenadine hydrochloride', 'Phasellus in felis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'finasteride', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzocain', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'hydroxyzine pamoate', 'Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'bacitracin zinc,neomycin sulfate, polymyxin b sulfate, pramoxine hcl', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Chlorpheniramine Maleate', 'Maecenas tincidunt lacus at velit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'fluvastatin sodium', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE, TITANIUM DIOXIDE', 'Nulla tempus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Arsenicum album, Calcarea carbonica, Graphites', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'diphenoxylate hydrochloride and atropine sulfate', 'Praesent id massa id nisl venenatis lacinia.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'PHENOL', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'levetiracetam', 'Integer ac leo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'SOLANUM NIGRUM TOP', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'nitroglycerin', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Folic Acid, Pyridoxine, Calcium Carbonate, Thiamine Mononitrate, Cholecalciferol, .Alpha.-Tocopherol, D-, Cyanocobalamin, Ferrous Fumarate, Magnesium Oxide, Riboflavin, Niacin, Ascorbic Acid, Cupric Sulfate, Vitamin A Palmitate, Zinc Oxide, Doconexent, and Ethyl Icosapentate', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OXYGEN', 'Donec posuere metus vitae ipsum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Titanium dioxide', 'Nullam porttitor lacus at turpis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aconitum napellus, Aethusa cynapium, Argentum nitricum, Arsenicum album, Borago officinalis, Bryonia, Castanea sativa, flos, Cytisus scoparius, Digitalis purpurea, Eriodictyon californicum, Jatropha curcas, Laurocerasus, Lolium temulentum, Mancinella, Murex purpurea, Rhus toxicodendron, Sinapis arvensis, flos, Spongia tosta', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'salicylic acid', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Homosalate and Octinoxate and Octisalate and Avobenzone and Octocrylene and Oxybenzone', 'Morbi porttitor lorem id ligula.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levetiracetam', 'Aenean lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'SILICON DIOXIDE', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cocoa butter, Phenylephrine HCl, Shark liver oil', 'In hac habitasse platea dictumst.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Dextromethorphan HBr, Phenylephreine HCI', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aquilinum Taraxicum', 'Nulla facilisi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'indomethacin', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nicotine polacrilex', 'Curabitur in libero ut massa volutpat convallis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Olanzapine', 'Duis ac nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ziprasidone HCl', 'Phasellus sit amet erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Bacitracin Zinc and Polymyxin B Sulfate', 'Aenean lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Temazepam', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'HYDROMORPHONE HYDROCHLORIDE', 'Morbi quis tortor id nulla ultrices aliquet.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lovastatin', 'Phasellus id sapien in sapien iaculis congue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Divalproex Sodium', 'Aliquam erat volutpat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TRAMADOL HYDROCHLORIDE', 'Aenean auctor gravida sem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'insulin aspart', 'Proin eu mi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ibuprofen', 'Ut at dolor quis odio consequat varius.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ibuprofen', 'Donec posuere metus vitae ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Warfarin Sodium', 'Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Bupropion Hydrochloride', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ACETAMINOPHEN', 'Morbi non quam nec dui luctus rutrum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'vinorelbine tartrate', 'Morbi non quam nec dui luctus rutrum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lamotrigine', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'PYRITHIONE ZINC', 'Vestibulum sed magna at nunc commodo placerat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Naltrexone Hydrochloride', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'SALICYLIC ACID', 'Mauris sit amet eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'telmisartan and hydrochlorothiazide', 'Morbi non quam nec dui luctus rutrum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Atenolol and Chlorthalidone', 'Suspendisse ornare consequat lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Fluconazole', 'Nunc nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diclofenac Sodium', 'Nam dui.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Allergenic Extracts Alum Precipitated', 'Ut at dolor quis odio consequat varius.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'bupropion hydrobromide', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'risperidone', 'Suspendisse potenti.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'CP2D/AS-3 Anticoagulant and Additive System', 'Nulla facilisi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Helium', 'Nulla facilisi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'DEXTROSE and SODIUM CHLORIDE', 'Phasellus in felis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Potassium Chloride', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ipratropium Bromide', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Scleranthus,', 'Suspendisse potenti.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'Proin eu mi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Pinchot Juniper', 'Praesent blandit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Dextromethorphan Hydrobromide, Doxylamine succinate', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lisinopril', 'Etiam faucibus cursus urna.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Salicylic Acid', 'Donec semper sapien a libero.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'pregabalin', 'Nulla tellus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cinnamic Acid, Phloridzinum, ATP, Argentum Nitricum, Beet Sugar, D-Ribose, Fructose, Dextrose, Grape Sugar (Syrup), Lycopodium Clavatum,', 'Suspendisse potenti.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Thuja occidentalis', 'In congue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Methyl Salicylate, Camphor, Menthol', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diphenhydramine HCl', 'Morbi a ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Loperamide Hydrochloride', 'Aenean auctor gravida sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Megestrol Acetate', 'Proin risus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aspirin', 'In hac habitasse platea dictumst.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BROMPHENIRAMINE MALEATE, PHENYLEPHRINE HYDROCHLORIDE', 'Vestibulum rutrum rutrum neque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ketotifen Fumarate', 'Morbi a ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Pyrithione Zinc', 'Aliquam erat volutpat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Diphenhydramine HCl', 'Integer tincidunt ante vel ipsum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ciclesonide', 'Donec quis orci eget orci vehicula condimentum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Amlodipine besylate', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE', 'Nulla ut erat id mauris vulputate elementum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate Titanium Dioxide', 'Ut tellus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'NICOTINE', 'In blandit ultrices enim.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Carbamazepine', 'Nulla mollis molestie lorem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Fentanyl Citrate', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Penicillin V Potassium', 'Cras non velit nec nisi vulputate nonummy.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Codeine Phosphate, Pseudoephedrine Hydrochloride, Brompheniramine Maleate', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OXYGEN', 'Donec posuere metus vitae ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'pravastatin sodium', 'Nullam molestie nibh in lectus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ensulizole, Octinoxate', 'In eleifend quam a odio.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Methyl Salicylate, Menthol, capsaicin', 'Integer ac neque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'fondaparinux sodium', 'Integer non velit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'estradiol valerate and estradiol valerate/dienogest', 'Morbi vel lectus in quam fringilla rhoncus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Heparin Sodium', 'Phasellus in felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ETHYL ALCOHOL', 'Duis consequat dui nec nisi volutpat eleifend.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE, Titanium Dioxide, Zinc Oxide', 'In congue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nifedipine', 'Nulla justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen and Phenylephrine HCl', 'Donec ut mauris eget massa tempor convallis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Oxymetazoline HCl', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'PYRITHIONE ZINC', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Menthol, Methyl salicylate', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ibuprofen', 'Proin eu mi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'temazepam', 'Etiam faucibus cursus urna.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'cetrorelix acetate', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ibuprofen', 'Pellentesque at nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'POVIDONE-IODINE', 'Curabitur gravida nisi at nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OYSTER SHELL CALCIUM CARBONATE, CRUDE, GOLDENSEAL, POTASSIUM DICHROMATE, and PULSATILLA VULGARIS', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Amlodipine Besylate and Benazepril Hydrochloride', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'hypromellose, tetrahydrozoline HCl, zinc sulfate', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Oxygen Helium Mixture 30/70', 'Mauris ullamcorper purus sit amet nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzocaine', 'Sed accumsan felis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'Curabitur convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TETRAHYDROZOLINE HYDROCHLORIDE AND ZINC SULFATE', 'Aliquam sit amet diam in magna bibendum imperdiet.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BUPIVACAINE HYDROCHLORIDE', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ethyl Alcohol', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'fluconazole', 'Praesent blandit lacinia erat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Baptisia Tinctoria, Echinacea, Allium Cepa, Ambrosia Artemisiaefolia, Arsenicum Album, Euphrasia Officinalis', 'Phasellus in felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'DOXYCYCLINE', 'Maecenas tincidunt lacus at velit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'AVOBENZONE, OCTINOXATE, OCTISALATE', 'Duis mattis egestas metus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Naproxen Sodium', 'Quisque id justo sit amet sapien dignissim vestibulum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Pigweed Rough Redroot', 'Nunc nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ciprofloxacin', 'Aliquam non mauris.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ondansetron hydrochloride', 'Integer ac neque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate, Octisalate, Oxybenzone, Avobenzone, Octocrylene', 'Sed vel enim sit amet nunc viverra dapibus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sulfamethoxazole and Trimethoprim', 'In eleifend quam a odio.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Donepezil Hydrochloride', 'Vestibulum rutrum rutrum neque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Propafenone hydrochloride', 'Vestibulum rutrum rutrum neque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Simethicone', 'Phasellus in felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'LOPERAMIDE HYDROCHLORIDE', 'Morbi non quam nec dui luctus rutrum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Morphine Sulfate', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nystatin', 'Integer non velit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nicotine Polacrilex', 'Pellentesque eget nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Bisacodyl', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Clonidine Hydrochloride', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Standardized Grass Pollen, Redtop', 'Nam nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'metoclopramide hydrochloride', 'Proin at turpis a pede posuere nonummy.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Fexofenadine HCl', 'Nunc purus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hyoscyamine Sulfate', 'Vivamus in felis eu sapien cursus vestibulum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'PSYLLIUM HUSK', 'Pellentesque at nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Arnica montana, Calendula officinalis, Echinacea, Hydrastis canadensis, Myrrha, Phytolacca Decandra, Tarasacum officinale, Trifolium pratense, Trigonella foenum-graecum, Urtica cioica, Propolis, Adrenalinum, Gunpowder, Thymus (suis), Thyroidinum (suis), Arsenicum album, Cocculus indicus, Iridium metallicum, Lycopodium clavatum Phosphorus,', 'Vestibulum ac est lacinia nisi venenatis tristique.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Methyl Salicylate and Menthol', 'Etiam vel augue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Banana', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Meperidine Hydrochloride', 'Integer ac leo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'FOSPHENYTOIN SODIUM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Calcitriol', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Haloperidol', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Salicylic Acid', 'Praesent blandit lacinia erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Phenazopyridine', 'Aliquam quis turpis eget elit sodales scelerisque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Docusate Sodium', 'Integer ac leo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'octreotide acetate', 'Nulla suscipit ligula in lacus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Dextromethorphan HBr', 'Proin eu mi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BUMETANIDE', 'Etiam vel augue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ibuprofen, Pseudoephedrine Hydrochloride', 'Nam tristique tortor eu pede.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'acyclovir', 'Nulla justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ammonia n-13', 'Proin at turpis a pede posuere nonummy.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'zinc pyrithione, panthenol, niacinamide, biotin', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ramipril', 'Etiam faucibus cursus urna.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Fluconazole', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Topiramate', 'Donec semper sapien a libero.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Anacardium orientale, Belladonna, Hyoscyamus', 'Vestibulum sed magna at nunc commodo placerat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'darifenacin', 'In hac habitasse platea dictumst.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Chlordiazepoxide Hydrochloride and Clidinium Bromide', 'Duis bibendum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aralia Quinquefolia, Damiana, Hydrocotyle Asiatica, Juniperus Virginiana, Pareira Brava, Sabal Serrulata, Thuja Occidentalis, Clematis Erecta', 'Suspendisse ornare consequat lectus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levofloxacin', 'Maecenas ut massa quis augue luctus tincidunt.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ESZOPICLONE', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Calcium carbonate', 'Quisque porta volutpat erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE and OXYBENZONE', 'Nullam porttitor lacus at turpis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzalkonium Chloride', 'Nam tristique tortor eu pede.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'metoprolol tartrate', 'Mauris ullamcorper purus sit amet nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Arsenicum alb., clacarea iodata, Carbo animalis, Conium, Graphites, Hydrastis, Iodium, Kreosotum, Lachesis, Phosphorus, Sabina, Secale, Sepia, Silicea, Thlaspi, Thuja occ., Thyroidinum, Trillium pendulum, Ustilago maidis', 'Praesent blandit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ISOPROPYL ALCOHOL', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BENZETHONIUM CHLORIDE', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sulfur', 'Curabitur gravida nisi at nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ACYCLOVIR SODIUM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lidocaine Hydrochloride', 'Mauris sit amet eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Doxycycline Hyclate', 'Suspendisse accumsan tortor quis turpis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Bumetanide', 'Phasellus in felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Duloxetine', 'Sed sagittis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ZONISAMIDE', 'Nulla nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate and Titanium Dioxide', 'Vivamus vestibulum sagittis sapien.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ENALAPRIL MALEATE', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levothyroxine sodium', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Imipramine Hydrochloride', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aspirin, Chlorpheniramine maleate, and Phenylephrine bitartrate', 'Duis bibendum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sodium Fluoride', 'Vestibulum sed magna at nunc commodo placerat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Atovaquone and Proguanil Hydrochloride', 'Pellentesque eget nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'rizatriptan benzoate', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'calcium carbonate', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'doxycycline hyclate', 'Donec dapibus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'levothyroxine sodium', 'Vivamus vestibulum sagittis sapien.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Naproxen Sodium', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Amlodipine Besylate', 'Aenean auctor gravida sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE, OCTINOXATE, OCTISALATE', 'Etiam faucibus cursus urna.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'bromfenac', 'In hac habitasse platea dictumst.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Isosorbide mononitrate', 'Suspendisse potenti.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OXYGEN', 'Cras pellentesque volutpat dui.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzoyl Peroxide', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aluminum Zirconium Pentachlorohydrex Gly', 'Etiam pretium iaculis justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'furosemide', 'Duis ac nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Birch Black', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Jute', 'Phasellus id sapien in sapien iaculis congue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'FLUOXETINE HYDROCHLORIDE, CHOLINE', 'Sed accumsan felis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'Nullam porttitor lacus at turpis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Antiseptic Surgical Scrub', 'Aliquam quis turpis eget elit sodales scelerisque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Esomeprazole sodium', 'Vivamus tortor.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ESTROGENS, CONJUGATED', 'Donec posuere metus vitae ipsum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'calcium', 'Morbi vel lectus in quam fringilla rhoncus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrogen Peroxide', 'In blandit ultrices enim.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Glycerin', 'Morbi non quam nec dui luctus rutrum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Standardized Perennial Rye Grass Pollen', 'Duis mattis egestas metus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'LEVOTHYROXINE SODIUM', 'Nam nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Montelukast Sodium', 'Praesent blandit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'haloperidol', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Water', 'Aenean fermentum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diltiazem Hydrochloride', 'Nulla ut erat id mauris vulputate elementum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ENALAPRIL MALEATE', 'Donec vitae nisi.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Titanium dioxide', 'Vivamus tortor.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrocortisone', 'Nunc rhoncus dui vel sem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydromorphone HCl', 'Phasellus sit amet erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Minoxidil', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE, OCTSALATE, AVOBENZONE', 'Duis consequat dui nec nisi volutpat eleifend.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE and TITANIUM DIOXIDE', 'Praesent lectus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'fluorouracil', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nicotine Polacrilex', 'Mauris sit amet eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE, ZINC OXIDE', 'Vestibulum ac est lacinia nisi venenatis tristique.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Menthol and Camphor', 'Nulla ac enim.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lisinopril', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ragweed False Bur', 'Curabitur convallis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Anticoagulant Citrate Phosphate Dextrose Adenine', 'Sed ante.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'levalbuterol hydrochloride', 'Nulla tellus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Indomethacin', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, Aspirin, Caffeine', 'Donec posuere metus vitae ipsum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'RISPERIDONE', 'Nulla tellus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Trazodone Hydrochloride', 'Donec ut dolor.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sodium fluoride', 'Duis aliquam convallis nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Bacitracin Zinc', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Agnus, Aralia quinquefolia, Baryta carb., Berber. vulg., Bryonia, Caladium seguinum, Cantharis, Causticum, Chelidonium majus, Cinchona, Conium, Gaultheria procumbens, Graphites, Kali carb., Lycopodium, Nux vom., Onosmodium virginianum, Phosphorus, Sabal, Selenium, Sepia, Silicea, Staphysag., Hydrastis, Thuja occ', 'Maecenas rhoncus aliquam lacus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'nitroglycerin', 'Proin at turpis a pede posuere nonummy.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'EUCALYPTOL', 'Ut at dolor quis odio consequat varius.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diphenhydramine hydrochloride, zinc acetate', 'Sed vel enim sit amet nunc viverra dapibus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Phenazopyridine', 'Etiam justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ergotamine Tartrate and Caffeine', 'In sagittis dui vel nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Phenylephrine HCl', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Naproxen Sodium', 'Aenean auctor gravida sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sertraline Hydrochloride', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lidocaine', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Phenol', 'Proin risus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Butalbital, Acetaminophen, and Caffeine', 'Duis at velit eu est congue elementum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Dextroamphetamine saccharate, amphetamine aspartate monohydrate, dextroamphetamine sulfate and amphetamine sulfate', 'Nulla tellus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Treatment Set TS348563', 'Pellentesque eget nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Etoposide', 'Curabitur in libero ut massa volutpat convallis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate, Octisalate, and Titanium Dioxide', 'Pellentesque viverra pede ac diam.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'GUAIFENESIN', 'In quis justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Doxycycline Hyclate', 'Vivamus vel nulla eget eros elementum pellentesque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE OCTISALATE OXYBENZONE', 'Morbi a ipsum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrochlorothiazide', 'Aenean fermentum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Russian Thistle', 'Sed sagittis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ethyl Alcohol', 'Donec posuere metus vitae ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Arnica montana, Calcarea fluorica, Calcarea phosphorica, Calendula officinalis, Graphites, Hydrofluoricum acidum, Phytolacca decandra, Sabina, Silicea, Thiosinaminum and Thuja occidentalis', 'Pellentesque at nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Antimon. crud., Bryonia, Calc.carb., Causticum, Dulcamara, Graphites, Lycopodium, Merc. sulph. rub., Nat. carb., Nitricum ac., Nux vom., Rhus toxicodendron, Sabina, Sepia, Silicea, Staphysag., Sulphur, Thuja occ., Taraxacum', 'Sed sagittis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Carbamazepine', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levetiracetam', 'Quisque ut erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Trazodone Hydrochloride', 'Integer a nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Clonazepam', 'Quisque id justo sit amet sapien dignissim vestibulum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrocortisone', 'Etiam pretium iaculis justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzoyl Peroxide', 'Donec ut mauris eget massa tempor convallis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ziprasidone Hydrochloride', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Bacitracin, Neomycin, Polymyxin B, Pramoxine HCl', 'Integer non velit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aconitum napellus, Hypericum perforatum, Lycopodium clavatum, Phosphorus, Rhus toxicodendron, Secale cornutum', 'Morbi non quam nec dui luctus rutrum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Guanfacine Hydrochloride', 'Cras in purus eu magna vulputate luctus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ethyl Alcohol', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Aluminum Sesquichlorohydrate', 'Suspendisse accumsan tortor quis turpis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Pollens - Weeds, Marshelder/Poverty Mix', 'Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ensulizole, Octinoxate, Octocrylene, and Oxybenzone', 'Sed ante.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Baryta carbonica, Belladonna atropa, Phytolacca decandra', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Avobenzone, Octisalate, Zinc Oxide, Octinoxate, and Oxybenzone', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'estradiol', 'Nulla tempus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'pravastatin sodium', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'warfarin sodium', 'In eleifend quam a odio.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Rough Marsh Elder', 'Praesent blandit.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Benzocaine, Menthol, Cetylpyridinium Chloride', 'Duis bibendum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'DOG EPITHELIA', 'Fusce consequat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cetirizine Hydrochloride', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ZINC OXIDE', 'Maecenas pulvinar lobortis est.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Anti-bacterial Hand Wash', 'Nulla tellus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Demeclocycline Hydrochloride', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen and Caffeine', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ziconotide', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sotalol Hydrochloride', 'Nulla suscipit ligula in lacus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ofloxacin', 'Phasellus in felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Doxazosin Mesylate', 'Quisque ut erat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diethylpropion Hydrochloride', 'Nunc nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Avobenzone, Homosalate, Octisalate, and Octocrylene', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Zinc oxide', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Glycerin', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Felodipine', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'tramadol hydrochloride', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Clotrimazole', 'Integer ac leo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nux vomica, Kali arsenicum, Berberis vulgaris, Graphites, Arsenicum album, Hepar sulphuris calcareum, Arsenicum sulphuratum rubrum', 'Mauris ullamcorper purus sit amet nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'betamethasone dipropionate', 'Etiam vel augue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Oxybutynin Chloride', 'Aenean lectus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ALPRAZOLAM', 'Nullam porttitor lacus at turpis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'oxycodone hydrochloride', 'Proin interdum mauris non ligula pellentesque ultrices.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ranitidine', 'Vivamus vestibulum sagittis sapien.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'octisalate, homosalate, oxybenzone, avobenzone, and octocrylene', 'Curabitur in libero ut massa volutpat convallis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nitrous Oxide', 'Sed accumsan felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate, Octocrylene, Oxybenzone, and Zinc Oxide', 'In congue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Amoxicillin', 'In eleifend quam a odio.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'MINOXIDIL', 'Curabitur gravida nisi at nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Oxycodone Hydrochloride', 'Proin eu mi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Furosemide', 'Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Etodolac', 'Morbi a ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diclofenac Sodium', 'Vestibulum ac est lacinia nisi venenatis tristique.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Griseofulvin', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'THUJA OCCIDENTALIS LEAFY TWIG', 'Sed ante.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen and Diphenhydramine Hydrochloride', 'Vivamus tortor.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE, OCTISALATE, AVOBENZONE, OCTOCRYLENE', 'Morbi a ipsum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Alcohol', 'Sed sagittis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'SALINE ENEMA', 'Mauris sit amet eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Mepivacaine Hydrochloride', 'Maecenas pulvinar lobortis est.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cashew Nut Meat', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BENZOCAINE', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'BUPIVACAINE HYDROCHLORIDE', 'Aliquam non mauris.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cyclobenzaprine Hydrochloride', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Metoprolol Succinate', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'fluvoxamine maleate', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Tobramycin', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Kali bich, Pulsatilla, Hepar sulph , Thuja occ , Spigelia anth', 'Etiam vel augue.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Hydrocodone Bitartrate and Ibuprofen', 'Proin risus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'PETROLATUM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'carboxymethylcellulose sodium', 'Sed accumsan felis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Niacin', 'Fusce consequat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen, dextromethorphan HBr, doxylamine succinate, phenylephrine HCl', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Codeine Phosphate, Phenylephrine Hydrochloride', 'Donec ut dolor.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ondansetron Hydrochloride', 'Nulla ac enim.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Glyburide', 'Duis mattis egestas metus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Levetiracetam', 'Vestibulum rutrum rutrum neque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Cherry Plum, Clematis, Impatiens, Rock rose, Star of Bethlehem, ATP, Pineal, thymus', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Amoxicillin', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'FLUORIDE TREATMENT', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Calamine 8% and Zinc Oxide 8%', 'Morbi non lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'HYDROCODONE BITARTRATE', 'Nunc nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE, OCTOCRYLENE, and TITANIUM DIOXIDE', 'Nam tristique tortor eu pede.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ropinirole', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE', 'Mauris sit amet eros.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diphenhydramine Hydrochloride', 'In sagittis dui vel nisl.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'oxycodone hydrochloride', 'Etiam vel augue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'SALICYLIC ACID', 'Mauris sit amet eros.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Amlodipine Besylate and Benazepril HCL', 'Nulla ut erat id mauris vulputate elementum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Acetaminophen', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lidocaine Hydrochloride', 'Nunc purus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Norethindrone', 'Aliquam sit amet diam in magna bibendum imperdiet.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE', 'Etiam vel augue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'ALUMINUM SULFATE', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'acyclovir', 'Nam tristique tortor eu pede.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'nicotine', 'Suspendisse ornare consequat lectus.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Oxymetazoline HCl', 'Mauris lacinia sapien quis libero.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'nitrofurantoin (macrocrystals)', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'SODIUM CHLORIDE', 'In hac habitasse platea dictumst.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Chloroxylenol', 'Nunc nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'pseudomonas aeruginosa', 'Sed sagittis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Diclofenac Potassium', 'Nulla ac enim.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'TITANIUM DIOXIDE', 'Quisque porta volutpat erat.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'morphine sulfate', 'Nam nulla.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'propranolol hydrochloride', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE', 'Nulla suscipit ligula in lacus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'METHYL SALICYLATE', 'Phasellus id sapien in sapien iaculis congue.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Ramipril', 'Quisque id justo sit amet sapien dignissim vestibulum.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lovastatin', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'avobenzone, homosalate, octisalate, oxybenzone', 'In sagittis dui vel nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Homeopathic Liquid', 'Sed accumsan felis.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'OCTINOXATE and HYDROQUINONE', 'Vivamus in felis eu sapien cursus vestibulum.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'dimethicone', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'FAMOTIDINE', 'Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Terazosin Hydrochloride', 'Nullam varius.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Chlorhexidine Gluconate and Alcohol', 'Nulla justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Pistachio', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Tamarix gallica', 'Nulla mollis molestie lorem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Niacinamide 2%', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'venlafaxine hydrochloride', 'Duis ac nibh.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Magnesium Citrate', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Octinoxate', 'Aenean sit amet justo.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Budesonide', 'Ut tellus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'MORPHINE SULFATE', 'Proin interdum mauris non ligula pellentesque ultrices.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Nicotine Polacrilex', 'Proin eu mi.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'darunavir', 'Nunc rhoncus dui vel sem.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Midodrine Hydrochloride', 'Integer ac leo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'benzethonium chloride, benzocaine, and menthol', 'In hac habitasse platea dictumst.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Petrolatum', 'Donec dapibus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'amaranthus spinosus pollen', 'Donec ut mauris eget massa tempor convallis.', 1);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Lisinopril and Hydrochlorothiazide', 'Nulla tellus.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Titanium Dioxide', 'Aliquam quis turpis eget elit sodales scelerisque.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Sodium fluoride', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Loratadine', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'AVOBENZONE, OCTINOXATE', 'Morbi quis tortor id nulla ultrices aliquet.', 0);
insert into medicamento (medicamento_id, sustancia_activa, descripcion, es_riesgo) values (medicamento_seq.nextval, 'Candesartan cilexetil and Hydrochlorothiazide', 'Vivamus tortor.', 1);
